apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-nginx
  template:
    metadata:
      labels:
        app: react-nginx
    spec:
      containers:
      - name: react-nginx
        image: maryam767/react-nginx-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-nginx-service
spec:
  type: NodePort
  selector:
    app: react-nginx
  ports:
  - port: 80
    targetPort: 80
  # Change this from 30007 to 30008 or another free port between 30000-32767

